export const deepTopics=['MAT-PRO-01','MAT-PRO-02','MAT-PRO-03','MAT-PRO-04','MAT-FUN-02','MAT-FUN-03'];
const f=(expected,label='Ergebnis',unit='')=>({key:'value',label,unit,expected,tolerance:0.000001});
const choice=(expected,options)=>({...f(expected,'Deine Entscheidung'),options:options.map((label,i)=>({value:String(i+1),label}))});
const rows=[
 ['MAT-PRO-01','verstehen','reference','20 von 80 Jugendlichen fahren Rad. Welche Zahl ist hier der Grundwert?',choice(2,['20','80','25']),['Der Grundwert ist das Ganze.','Alle 80 Jugendlichen bilden die Bezugsgruppe.'],['Grundwert G = 80. Der Anteil ist 20, der Prozentsatz 25 %.']],
 ['MAT-PRO-01','verstehen','unit','Eine Schule hat 300 Jugendliche. 60 kommen mit dem Bus. Was beschreibt 60/300 = 0,2?',choice(1,['Den Anteil: 20 %','Den Grundwert: 0,2 Personen','Den Prozentwert: 0,2 Personen']),['Der Quotient Anteil/Ganzes ist ein dimensionsloser Anteil.','Multipliziere 0,2 mit 100, um Prozent anzugeben.'],['60/300 = 0,2 = 20 %. Prozentwert 60; Grundwert 300.']],
 ['MAT-PRO-01','pruefung','compare','Verein A: 18 von 60 Mitgliedern sind Jugendliche. Verein B: 24 von 120. Um wie viele Prozentpunkte ist der Jugendanteil in A größer?',f(10,'Unterschied','Prozentpunkte'),['Vergleiche Anteile, nicht die absoluten Zahlen.','Berechne beide Prozentsätze und bilde ihre Differenz.'],['A: 18/60 = 30 %. B: 24/120 = 20 %.','Unterschied: 10 Prozentpunkte; nicht 10 % relative Zunahme.']],
 ['MAT-PRO-01','pruefung','combine','Eine Klasse hat 20 Jugendliche, davon 40 % Radfahrer. Eine andere hat 30, davon 20 % Radfahrer. Welcher Prozentsatz der insgesamt 50 Jugendlichen fährt Rad?',f(28,'Gesamtanteil','%'),['Die Klassen sind verschieden groß: nicht einfach die Prozentsätze mitteln.','Bestimme zuerst die Radfahrerzahlen, dann den Gesamtanteil.'],['8 + 6 = 14 Radfahrer.','14/50·100 = 28 %.']],
 ['MAT-PRO-02','verstehen','factor','Ein Preis sinkt um 15 %. Welcher Faktor berechnet den neuen Preis?',choice(2,['0,15','0,85','1,15']),['Der neue Preis enthält den verbleibenden Anteil.','100 % − 15 % = 85 %.'],['Neu = Alt·0,85. Mit 0,15 berechnet man nur den Rabatt.']],
 ['MAT-PRO-02','verstehen','error','Ein Preis von 80 € steigt um 25 %. Jemand rechnet 80 + 25 = 105 €. Bestimme den richtigen neuen Preis.',f(100,'Neuer Preis','€'),['25 % ist kein fester Eurobetrag.','Berechne 25 % von 80 und addiere die Änderung.'],['25 % von 80 = 20 €.','80 + 20 = 100 €.']],
 ['MAT-PRO-02','pruefung','compare','Angebot A: 120 € mit 20 % Rabatt. Angebot B: 110 € mit 10 % Rabatt. Um wie viele Euro ist A günstiger?',f(3,'Preisunterschied','€'),['Ein größerer Rabatt bedeutet nicht automatisch den niedrigeren Endpreis.','Berechne beide Endpreise und vergleiche.'],['A: 120·0,8 = 96 €. B: 110·0,9 = 99 €.','A ist 3 € günstiger.']],
 ['MAT-PRO-02','pruefung','threshold','Ein Rad kostet 240 €. Du hast 210 €. Welcher Rabatt in Prozent ist mindestens nötig, damit dein Geld reicht?',f(12.5,'Mindestrabatt','%'),['Berechne den fehlenden Betrag.','Beziehe den fehlenden Betrag auf den ursprünglichen Preis.'],['240−210 = 30 €.','30/240·100 = 12,5 %.']],
 ['MAT-PRO-03','verstehen','reverse-factor','Nach 20 % Rabatt kostet ein Artikel 64 €. Welcher Ansatz bestimmt den alten Preis?',choice(3,['64·0,8','64·1,2','64/0,8']),['64 € sind 80 % des alten Preises.','Die Umkehroperation zur Multiplikation ist Division.'],['Alt = 64/0,8 = 80 €.']],
 ['MAT-PRO-03','verstehen','error','Nach 25 % Rabatt kostet ein Spiel 60 €. Jemand erhöht 60 € um 25 %, um den alten Preis zu finden. Um wie viele Euro liegt dieses Ergebnis unter dem wirklichen alten Preis?',f(5,'Fehlbetrag','€'),['Die Erhöhung benutzt einen anderen Grundwert.','Vergleiche 60·1,25 mit 60/0,75.'],['Falscher Ansatz: 75 €. Alter Preis: 80 €.','Der Fehler beträgt 5 €.']],
 ['MAT-PRO-03','pruefung','reconstruct','Eine Rechnung nach 10 % Rabatt beträgt 135 €. Die ursprüngliche Rechnung bestand aus 30 € Material und Arbeitskosten. Wie hoch waren die ursprünglichen Arbeitskosten?',f(120,'Arbeitskosten','€'),['Rekonstruiere zuerst die ganze ursprüngliche Rechnung.','Ziehe die unveränderten ursprünglichen Materialkosten erst danach ab.'],['Ursprüngliche Rechnung: 135/0,9 = 150 €.','Arbeitskosten: 150−30 = 120 €.']],
 ['MAT-PRO-03','pruefung','compare','Ein Artikel kostet nach 20 % Rabatt 72 €, ein anderer nach 10 % Rabatt 81 €. Wie groß ist die Differenz ihrer ursprünglichen Preise?',f(0,'Differenz','€'),['Vergleiche die ursprünglichen Preise, nicht die Endpreise.','Teile jeden Endpreis durch seinen Faktor.'],['72/0,8 = 90 €; 81/0,9 = 90 €.','Die ursprünglichen Preise sind gleich: Differenz 0 €.']],
 ['MAT-PRO-04','verstehen','factor-product','Ein Preis steigt um 20 % und sinkt danach um 20 %. Welcher Gesamtfaktor gilt?',choice(1,['0,96','1','0,8']),['Die zweite Änderung nutzt den neuen Grundwert.','Multipliziere 1,2 und 0,8.'],['1,2·0,8 = 0,96. Insgesamt sinkt der Preis um 4 %.']],
 ['MAT-PRO-04','verstehen','order','Ein Preis wird um 10 % erhöht und um 20 % gesenkt. Ändert sich der Endpreis, wenn man die Reihenfolge vertauscht, ohne zwischenzeitliche Rundung?',choice(2,['Ja, immer','Nein, beide Faktoren ergeben dasselbe Produkt']),['Schreibe beide Reihenfolgen als Produkt.','Die Multiplikation der Faktoren ist vertauschbar.'],['Alt·1,1·0,8 = Alt·0,8·1,1 = Alt·0,88.']],
 ['MAT-PRO-04','pruefung','restore','Ein Preis von 100 € sinkt um 20 %. Um wie viel Prozent muss der neue Preis steigen, um wieder 100 € zu erreichen?',f(25,'Nötige Erhöhung','%'),['Der neue Grundwert ist 80 €.','Die fehlenden 20 € müssen auf 80 € bezogen werden.'],['20/80·100 = 25 %.','80·1,25 = 100 €.']],
 ['MAT-PRO-04','pruefung','compound','Ein Preis sinkt zweimal nacheinander um 10 %. Um wie viel Prozent ist er insgesamt gesunken?',f(19,'Gesamtrabatt','%'),['Multipliziere die beiden verbleibenden Anteile.','Vergleiche den Gesamtfaktor mit 1.'],['0,9·0,9 = 0,81.','1−0,81 = 0,19, also 19 %.']],
 ['MAT-FUN-02','verstehen','table','Eine Tabelle enthält (x|y): (0|4), (1|7), (2|10). Welche Gleichung passt?',choice(2,['y = 4x + 3','y = 3x + 4','y = 7x']),['Bei x = 0 liest du den Anfangswert ab.','Je zusätzlichem x steigt y um 3.'],['Anfangswert 4; Steigung 3. Deshalb y = 3x + 4.']],
 ['MAT-FUN-02','verstehen','slope','Die Gerade geht durch (1|5) und (3|9). Bestimme ihre Steigung.',f(2,'Steigung m'),['Steigung ist Änderung von y geteilt durch Änderung von x.','Nutze (9−5)/(3−1).'],['m = 4/2 = 2.']],
 ['MAT-FUN-02','pruefung','two-points','Ein Verleih kostet für 2 Stunden 11 € und für 5 Stunden 20 €. Die Kosten steigen linear. Bestimme die Grundgebühr.',f(5,'Grundgebühr','€'),['Bestimme aus den beiden Angaben zuerst den Stundenpreis.','Ziehe danach den Preis für 2 Stunden von 11 € ab.'],['m = (20−11)/(5−2) = 3 €/h.','n = 11−2·3 = 5 €.']],
 ['MAT-FUN-02','pruefung','intersection','Tarif A kostet A(x)=2x+12 €, Tarif B kostet B(x)=5x+3 €. Bei welcher Nutzungsdauer x sind beide gleich teuer?',f(3,'Nutzungsdauer','h'),['Am Schnittpunkt stimmen beide Kosten überein.','Setze 2x+12 = 5x+3 und löse.'],['9 = 3x, also x = 3 h.','Beide Tarife kosten dann 18 €.']],
 ['MAT-FUN-03','verstehen','meaning','f(x)=3x−6. Was bedeutet die Nullstelle x=2?',choice(2,['Bei x=0 beträgt y=2','Bei x=2 beträgt y=0','Der Graph steigt um 2']),['Die Nullstelle beschreibt eine Stelle auf der x-Achse.','Setze x=2 ein.'],['f(2)=0. Der Graph schneidet die x-Achse bei (2|0).']],
 ['MAT-FUN-03','verstehen','inverse','f(x)=4x+1. Für welches x beträgt der Funktionswert 13?',f(3,'Stelle x'),['Gesucht ist x, nicht f(13).','Setze 4x+1 = 13.'],['4x=12, also x=3. Probe: f(3)=13.']],
 ['MAT-FUN-03','pruefung','domain','Ein Tank enthält 60 Liter. Jede Minute fließen 4 Liter ab. Wie viele Minuten ist das Modell V(t)=60−4t höchstens sinnvoll, wenn kein negativer Inhalt erlaubt ist?',f(15,'Maximale Dauer','min'),['Der sinnvolle Zeitraum endet bei leerem Tank.','Setze V(t)=0.'],['60−4t=0, also t=15.','Für 0≤t≤15 ist der Inhalt nicht negativ. Danach ist das Modell nicht sinnvoll.']],
 ['MAT-FUN-03','pruefung','budget','Ein Ausflug kostet 35 € feste Gebühr und 8 € je Person. Das Budget beträgt 100 €. Wie viele Personen können höchstens teilnehmen?',f(8,'Höchste Personenzahl','Personen'),['Nach der festen Gebühr stehen 65 € zur Verfügung.','Teile durch 8 und beachte ganze Personen.'],['(100−35)/8=8,125. Höchstens 8 Personen.','Probe: 35+8·8=99 €; 9 Personen würden 107 € kosten.']]
];
export const depthTasks=rows.map(([topic,stage,family,prompt,field,hints,steps],i)=>({id:`DEPTH-${String(i+1).padStart(3,'0')}`,topic,stage,family,version:1,prompt,fields:[field],hints,steps,error:'Prüfe zuerst die Bezugsgröße oder die Bedeutung der gesuchten Größe. Ein Hinweis hilft dir beim Ansatz.',tools:false,transfer:stage==='pruefung',difficulty:stage==='pruefung'?3:1,origin:'Eigenentwicklung',source:'Eigene Vertiefung zu Prozentrechnung und linearen Funktionen'}));
export function familyOf(t){if(t.family)return t.family;if(t.topic==='MAT-PRO-01')return ['part','base','rate','part'][Number(t.id.slice(-3))-1]||'screening';if(t.topic==='MAT-FUN-03')return ['value','zero','value','zero'][Number(t.id.slice(-3))-1]||'screening';return t.topic+'-basis';}
export function learningPathHTML(t){
 return `<section class="card"><h2>Ein Thema, drei Schritte</h2><p>Starte dort, wo es für dich passt. Jede Einheit bleibt kurz. Eine richtige Auswahl allein belegt noch keine Erklärung.</p><div class="depth-stages">${[['verstehen','1 · Verstehen','Bezüge erkennen, Fehler untersuchen und Zusammenhänge deuten.'],['anwenden','2 · Selbst anwenden','Selbst rechnen; Hinweise nur dann nutzen, wenn du sie brauchst.'],['pruefung','3 · Prüfungsnah lösen','Neue Situationen, mehrere Schritte und passende Verfahren.']].map(([id,title,description])=>`<section><h3>${title}</h3><p>${description}</p><button class="btn primary" data-action="learn:${t.id}|${id}">Kurze Einheit starten</button></section>`).join('')}</div><details><summary>Erklärung und ein Beispiel</summary><p>${t.explanation}</p><p class="preline">${t.example}</p></details><details><summary>So prüfst du deinen Papierweg</summary><ul><li>Was ist gegeben und gesucht? Benenne Größen und Einheiten.</li><li>Warum passt dein Ansatz? Erkläre den entscheidenden Zusammenhang.</li><li>Rechne nachvollziehbar und prüfe das Ergebnis in der Situation.</li></ul><p>Vergleiche deinen Weg später mit dem Musterweg. Diese Selbstkontrolle wird nicht automatisch benotet.</p></details></section>`;
}
export function taskVisual(t){
 if(!['DEPTH-017','DEPTH-018'].includes(t.id))return '';
 const m=t.id==='DEPTH-017'?3:2,n=t.id==='DEPTH-017'?4:3;
 const point=x=>`${70+70*x},${260-16*(m*x+n)}`;
 return `<figure class="depth-figure"><svg viewBox="0 0 340 300" role="img" aria-label="Koordinatensystem: Gerade durch ${t.id==='DEPTH-017'?'(0|4), (1|7) und (2|10)':'(1|5) und (3|9)'}"><path d="M70 30V260H310" fill="none" stroke="currentColor"/><text x="315" y="280">x</text><text x="40" y="25">y</text>${[0,1,2,3].map(x=>`<text x="${66+70*x}" y="280">${x}</text>`).join('')}${[0,5,10].map(y=>`<path d="M65 ${260-16*y}H310" stroke="#dbe4eb"/><text x="40" y="${264-16*y}">${y}</text>`).join('')}<polyline points="${point(0)} ${point(3)}" fill="none" stroke="#007b70" stroke-width="3"/>${(t.id==='DEPTH-017'?[0,1,2]:[1,3]).map(x=>`<circle cx="${70+70*x}" cy="${260-16*(m*x+n)}" r="5" fill="#007b70"/><text x="${74+70*x}" y="${250-16*(m*x+n)}">(${x}|${m*x+n})</text>`).join('')}</svg><figcaption>Verbinde die Wertepaare mit dem Graphen. Gleiche Schritte auf der x-Achse führen bei einer Geraden zu gleichen Änderungen von y.</figcaption></figure>`;
}
